// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: game_state.proto

package goproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Simple GameState message with a string name
type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_game_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_game_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_game_state_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_game_state_proto protoreflect.FileDescriptor

const file_game_state_proto_rawDesc = "" +
	"\n" +
	"\x10game_state.proto\x12\tgamestate\"\x1f\n" +
	"\tGameState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameB\x85\x01\n" +
	"\rcom.gamestateB\x0eGameStateProtoP\x01Z github.com/ducksu-protos/goproto\xa2\x02\x03GXX\xaa\x02\tGamestate\xca\x02\tGamestate\xe2\x02\x15Gamestate\\GPBMetadata\xea\x02\tGamestateb\x06proto3"

var (
	file_game_state_proto_rawDescOnce sync.Once
	file_game_state_proto_rawDescData []byte
)

func file_game_state_proto_rawDescGZIP() []byte {
	file_game_state_proto_rawDescOnce.Do(func() {
		file_game_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_state_proto_rawDesc), len(file_game_state_proto_rawDesc)))
	})
	return file_game_state_proto_rawDescData
}

var file_game_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_game_state_proto_goTypes = []any{
	(*GameState)(nil), // 0: gamestate.GameState
}
var file_game_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_game_state_proto_init() }
func file_game_state_proto_init() {
	if File_game_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_state_proto_rawDesc), len(file_game_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_state_proto_goTypes,
		DependencyIndexes: file_game_state_proto_depIdxs,
		MessageInfos:      file_game_state_proto_msgTypes,
	}.Build()
	File_game_state_proto = out.File
	file_game_state_proto_goTypes = nil
	file_game_state_proto_depIdxs = nil
}
