// @generated by protoc-gen-es v2.7.0
// @generated from file game_state.proto (package gamestate, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file game_state.proto.
 */
export const file_game_state = /*@__PURE__*/
  fileDesc("ChBnYW1lX3N0YXRlLnByb3RvEglnYW1lc3RhdGUiGQoJR2FtZVN0YXRlEgwKBG5hbWUYASABKAlChQEKDWNvbS5nYW1lc3RhdGVCDkdhbWVTdGF0ZVByb3RvUAFaIGdpdGh1Yi5jb20vZHVja3N1LXByb3Rvcy9nb3Byb3RvogIDR1hYqgIJR2FtZXN0YXRlygIJR2FtZXN0YXRl4gIVR2FtZXN0YXRlXEdQQk1ldGFkYXRh6gIJR2FtZXN0YXRlYgZwcm90bzM");

/**
 * Describes the message gamestate.GameState.
 * Use `create(GameStateSchema)` to create a new message.
 */
export const GameStateSchema = /*@__PURE__*/
  messageDesc(file_game_state, 0);

