// @generated by protoc-gen-es v2.7.0
// @generated from file game_state.proto (package gamestate, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game_state.proto.
 */
export declare const file_game_state: GenFile;

/**
 * Simple GameState message with a string name
 *
 * @generated from message gamestate.GameState
 */
export declare type GameState = Message<"gamestate.GameState"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message gamestate.GameState.
 * Use `create(GameStateSchema)` to create a new message.
 */
export declare const GameStateSchema: GenMessage<GameState>;

